#!/usr/bin/env bash
#MISE description="Checks go.mod and go.sum are tidy"
#MISE sources=["go.mod", "go.sum"]
#MISE outputs={auto = true}

set -ex

if ! go mod tidy -diff; then
    echo "ERROR: go.mod and go.sum are out of sync"
    echo "Run 'go mod tidy' locally and commit the changes"
    exit 1
fi
