name: Pull Request

on:
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Run CI
        run: task ci

      - name: Report test results
        uses: ctrf-io/github-test-reporter@v1
        if: always()
        with:
          report-path: ./.out/ctrf-report.json
          pull-request: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
