name: Pull Request

on:
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: 1.21

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Run CI
        run: task ci

      - name: Report test results
        uses: ctrf-io/github-test-reporter@e67da0557d332ad40c7fa1bc59a530106e7d639b # v1
        if: always()
        with:
          report-path: ./.out/ctrf-report.json
          pull-request: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
